apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      version: "6.x"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    test:
      enabled: false
    loki:
      auth_enabled: false
      serviceMonitor:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        retention_period: 24h
        volume_enabled: true
      # https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem # we're storing on filesystem so there's no real persistence here.
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
        enabled: true
      ruler:
        enable_api: true
    minio:
      enabled: true
    lokiCanary:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    gateway:
      ingress:
        enabled: true  
        ingressClassName: nginx
        hosts:
          - host: ""
            paths:
              - path: /loki
                pathType: Prefix
        tls:
