---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: rabbitmq
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values:
    auth:
      username: admin
      password: admin
    service:
      type: NodePort
      nodePorts:
        amqp: 30500
        amqpTls: 30501
        dist: 30502
        manager: 30503
        metrics: 30504
        epmd: 30505