apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 5m
  dependsOn:
    - name: grafana
  chart:
    spec:
      version: "27.x"
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  values:
    alertmanager:
      enabled: false
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
